# -*- coding: utf-8 -*-
"""Asignación1_MetMat1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNgf-Yaab5tsG7w1zSBZ8X-4qwY-gAY7
"""

import sympy as sp
from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

uploaded = files.upload()

uploaded = files.upload()

df_ref = pd.read_excel("Datos estaciones AMB PM2.5.xlsx")
df_sensor = pd.read_excel("pm25_sensor.xlsx")

df_ref.to_csv("Datos_estaciones_AMB_PM25.csv")
df_sensor.to_csv("pm25_sensor.csv")

df_ref = pd.read_csv('Datos_estaciones_AMB_PM25.csv', skiprows=[1])
df_ref["PM2.5"] = df_ref["PM2.5"].replace("NoData", pd.NA)
df_ref["PM2.5"] = pd.to_numeric(df_ref["PM2.5"], errors="coerce")
df_ref['rolling'] = df_ref['PM2.5'].rolling(window=22).mean()

import matplotlib.dates as mdates

# --- Limpiar datos ---
df_ref["PM2.5"] = pd.to_numeric(df_ref["PM2.5"], errors="coerce")
df_ref = df_ref.dropna(subset=["PM2.5"])

# Rolling promedio móvil para suavizar
df_ref["rolling"] = df_ref["PM2.5"].rolling(window=22).mean()

# --- Graficar ---
plt.figure(figsize=(12,6))
plt.plot(df_ref["fecha_hora_med"], df_ref["PM2.5"], color="blue", alpha=0.6, label="PM2.5 original")
plt.plot(df_ref["fecha_hora_med"], df_ref["rolling"], color="red", linewidth=2, label="Rolling (ventana=22)")

plt.gca().xaxis.set_major_locator(mdates.AutoDateLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))

plt.xlabel("Fecha y hora")
plt.ylabel("PM2.5")
plt.title("Serie temporal PM2.5 - Estación AMB")
plt.legend()
plt.grid(alpha=0.4)
plt.tight_layout()
plt.show()

# Rolling promedio
df_sensor['rolling'] = df_sensor['pm25'].rolling(window=22).mean()

# --- Graficar ---
plt.figure(figsize=(12,6))
plt.plot(df_sensor.index, df_sensor["pm25"], color="blue", alpha=0.6, label="PM2.5 original")
plt.plot(df_sensor.index, df_sensor["rolling"], color="red", linewidth=2, label="Rolling (ventana=22)")

plt.gca().xaxis.set_major_locator(mdates.AutoDateLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))

plt.xlabel("Fecha y hora")
plt.ylabel("PM2.5")
plt.title("Serie temporal PM2.5 - Estación AMB")
plt.legend()
plt.grid(alpha=0.4)
plt.tight_layout()
plt.show()

# 1. Convertir a datetime y poner fecha como índice
df_sensor = df_sensor.reset_index()
df_ref = df_ref.reset_index()
if 'unnamed:0' in df_sensor.columns:
    df_sensor = df_sensor.drop(columns=['unnamed:0'])
if 'unnamed:0' in df_ref.columns:
    df_ref = df_ref.drop(columns=['unnamed:0'])
df_sensor['time'] = pd.to_datetime(df_sensor['time'])
df_ref['fecha_hora_med'] = pd.to_datetime(df_ref['fecha_hora_med'])
df_sensor = df_sensor.set_index('time')
df_ref = df_ref.set_index('fecha_hora_med')

# 2. Opcional: calcular rolling promedio
df_sensor['rolling'] = df_sensor['pm25'].rolling(window=18, min_periods=1).mean()
df_ref['rolling'] = df_ref['PM2.5'].rolling(window=24, min_periods=1).mean()

# 3. Graficar
plt.figure(figsize=(10,5))
plt.plot(df_sensor.index, df_sensor['rolling'], label='df_sensor Rolling', color='red')
plt.plot(df_ref.index, df_ref['rolling'], label='df_ref Rolling', color='blue')
plt.xlabel("Fecha")
plt.ylabel("Promedio móvil PM2.5")
plt.title("Comparación de rollings df_sensor y df_ref")
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the data again within this cell to ensure correct processing
ref = pd.read_excel("Datos estaciones AMB PM2.5.xlsx")
cal = pd.read_excel("pm25_sensor.xlsx")

# Ensure time columns are datetime
ref["fecha_hora_med"] = pd.to_datetime(ref["fecha_hora_med"], errors="coerce")
cal["time"] = pd.to_datetime(cal["time"], errors="coerce")

# Handle non-numeric values in 'pm25' columns
# Replace 'NoData' with NaN before converting to numeric
ref['PM2.5'] = ref['PM2.5'].replace('NoData', np.nan)
cal['pm25'] = cal['pm25'].replace('NoData', np.nan)

ref['PM2.5'] = pd.to_numeric(ref['PM2.5'], errors='coerce')
cal['pm25'] = pd.to_numeric(cal['pm25'], errors='coerce')

# Set time columns as index
ref = ref.set_index("fecha_hora_med")
cal = cal.set_index("time")

# Define the common range and filter by index
inicio = "2018-11-03"
fin = "2019-08-31"

df_ref = ref[(ref.index >= inicio) & (ref.index <= fin)].copy()
df_sensor = cal[(cal.index >= inicio) & (cal.index <= fin)].copy()


# === 1. Asegurar que los índices de tiempo estén sin tz ===
# Already handled by setting index and filtering within this cell

# === 2. Resample a 30 minutos (base común más fina) y merge ===
df_ref_res   = df_ref.resample("30min").mean().rename(columns={"PM2.5": "pm25_ref"})
df_sens_res  = df_sensor.resample("30min").mean().rename(columns={"pm25": "pm25_cal"})

# Remove timezone information before concatenation
df_ref_res.index = df_ref_res.index.tz_localize(None)
df_sens_res.index = df_sens_res.index.tz_localize(None)


df_merged = pd.concat([df_ref_res, df_sens_res], axis=1).dropna(how="any")

# === 3. Distancia euclídea total y por día ===
diff = df_merged["pm25_ref"] - df_merged["pm25_cal"]
euclid_total = np.sqrt(np.nansum(diff**2))
print(f"Distancia euclídea TOTAL (sin rolling): {euclid_total:.4f}")

df_merged["date"] = df_merged.index.date
dist_by_day = (
    df_merged.dropna(subset=["pm25_ref","pm25_cal"])
    .groupby("date")
    .apply(lambda g: np.sqrt(np.nansum((g["pm25_ref"] - g["pm25_cal"])**2)), include_groups=False)
)
print("\nDistancias euclídeas por día (primeras filas):")
print(dist_by_day.head())

# === 4. Distancia y RMSE para diferentes ventanas (basadas en tiempo) ===
ventanas = ["30min", "1.5h", "3h", "5h", "7h", "9h"]  # puedes cambiar a las que quieras
resultados = []

for v in ventanas:
    ref_roll  = df_merged["pm25_ref"].rolling(window=v, min_periods=1).mean()
    sens_roll = df_merged["pm25_cal"].rolling(window=v, min_periods=1).mean()
    mask = ~(ref_roll.isna() | sens_roll.isna())
    dif  = ref_roll[mask] - sens_roll[mask]
    n    = int(mask.sum())
    euclid = np.sqrt(np.nansum(dif**2))
    rmse   = np.sqrt(np.nanmean(dif**2))
    resultados.append([v, euclid, rmse, n])

df_results = pd.DataFrame(
    resultados,
    columns=["ventana","euclid_total","rmse","n_puntos"]
).set_index("ventana")

print("\nResumen de distancias por ventana:")
print(df_results)

# === 5. Gráficas ===
plt.figure(figsize=(6,4))
plt.plot(df_results.index, df_results["euclid_total"], marker='o')
plt.xlabel("Ventana")
plt.ylabel("Distancia euclídea total")
plt.title("Distancia total vs ventana de promedio móvil")
plt.grid(True)
plt.show()

plt.figure(figsize=(6,4))
plt.plot(df_results.index, df_results["rmse"], marker='o', color="orange")
plt.xlabel("Ventana")
plt.ylabel("RMSE (µg/m³)")
plt.title("RMSE vs ventana de promedio móvil")
plt.grid(True)
plt.show()

import pandas as pd
import numpy as np

# Cargar los datos
ref = pd.read_excel("Datos estaciones AMB PM2.5.xlsx")
cal = pd.read_excel("pm25_sensor.xlsx")

# Asegurar que las columnas de tiempo son datetime
ref["fecha_hora_med"] = pd.to_datetime(ref["fecha_hora_med"], errors="coerce")
cal["time"] = pd.to_datetime(cal["time"], errors="coerce")

# Reemplazar valores no numéricos
ref['PM2.5'] = ref['PM2.5'].replace('NoData', np.nan)
cal['pm25'] = cal['pm25'].replace('NoData', np.nan)

ref['PM2.5'] = pd.to_numeric(ref['PM2.5'], errors='coerce')
cal['pm25'] = pd.to_numeric(cal['pm25'], errors='coerce')

# Usar columna de tiempo como índice
ref = ref.set_index("fecha_hora_med")
cal = cal.set_index("time")

# Definir rango común
inicio = "2018-11-03"
fin = "2019-08-31"

df_ref = ref[(ref.index >= inicio) & (ref.index <= fin)].copy()
df_sensor = cal[(cal.index >= inicio) & (cal.index <= fin)].copy()

# Re-muestreo en ventanas de 9 horas
ref_resamp = df_ref['PM2.5'].resample("9h").mean()
cal_resamp = df_sensor['pm25'].resample("9h").mean()

# Eliminar información de zona horaria
ref_resamp.index = ref_resamp.index.tz_localize(None)
cal_resamp.index = cal_resamp.index.tz_localize(None)

# Combinar ambos conjuntos de datos
df = pd.concat([ref_resamp, cal_resamp], axis=1, keys=["ref", "df_sensor"])
df = df.dropna()

# Renombrar columnas
df.columns = ["ref_pm25", "cal_pm25"]

# Número de ventanas
n_ventanas = len(df)
print(f"Número de ventanas de 9 horas = {n_ventanas}")

# Guardar resultados en un archivo Excel y CSV
df.to_excel("ventanas_9h_PM25.xlsx")
df.to_csv("ventanas_9h_PM25.csv", index=True)

print("✅ Resultados guardados en 'ventanas_9h_PM25.xlsx' y 'ventanas_9h_PM25.csv'")
print("Resultados subidos en el informe")

from sklearn.linear_model import LinearRegression

# Variables X (sensor) y Y (referencia)
X = df["cal_pm25"].values.reshape(-1, 1)
Y = df["ref_pm25"].values

# Ajuste lineal por mínimos cuadrados sin intercepto
modelo = LinearRegression(fit_intercept=False)
modelo.fit(X, Y)

alpha = modelo.coef_[0]   # pendiente
r2 = modelo.score(X, Y)   # coeficiente de determinación

print(f"Modelo ajustado: f(x) = {alpha:.4f} * x")
print(f"R^2 = {r2:.4f}")
print(f"Número de puntos usados = {len(X)}")

# Graficar
plt.figure(figsize=(8,6))
plt.scatter(X, Y, alpha=0.5, label="Promedios 9h (datos)")
plt.plot(X, modelo.predict(X), color="red", label=f"Ajuste lineal\nf(x)={alpha:.2f}x")
plt.xlabel("Sensor (pm25 calibrar)")
plt.ylabel("Referencia (pm25)")
plt.title("Ajuste lineal sin intercepto (ventanas de 9h)")
plt.legend()
plt.grid(True)
plt.show()

# Definir tolerancia (ejemplo: 10% del valor de referencia)
tol = 0.10

# Predicción del modelo
Y_pred = modelo.predict(X)

# Error relativo
error_rel = np.abs(Y - Y_pred) / Y

# Seleccionar los puntos dentro de tolerancia
validos = df[error_rel <= tol]

# Alcance en el eje del sensor (X)
alcance_min = validos["cal_pm25"].min()
alcance_max = validos["cal_pm25"].max()

print(f"Alcance válido en sensor (pm25): {alcance_min:.2f} – {alcance_max:.2f}")
print(f"Número de puntos dentro de tolerancia: {len(validos)} de {len(df)}")

# === División del conjunto en dos mitades ===
n = len(df)
df_train = df.iloc[:n//2]   # primera mitad
df_test  = df.iloc[n//2:]   # segunda mitad

# Modelo con la primera mitad
X_train = df_train["cal_pm25"].values.reshape(-1, 1)
Y_train = df_train["ref_pm25"].values

modelo = LinearRegression()
modelo.fit(X_train, Y_train)

# Predicciones en la segunda mitad
X_test = df_test["cal_pm25"].values.reshape(-1, 1)
Y_test = df_test["ref_pm25"].values
Y_pred = modelo.predict(X_test)

# Calcular error relativo
error_rel = np.abs(Y_test - Y_pred) / Y_test

# Seleccionar predicciones dentro de la tolerancia (ej: 10%)
tol = 0.10
validos = df_test[error_rel <= tol]

# Alcance de predicción dentro de tolerancia
alcance_min = validos["cal_pm25"].min()
alcance_max = validos["cal_pm25"].max()

print(f"Alcance de predicción válido (sensor): {alcance_min:.2f} – {alcance_max:.2f}")
print(f"Puntos válidos: {len(validos)} de {len(df_test)} en la segunda mitad")

# --- Gráfica de predicción vs referencia en la segunda mitad ---
plt.figure(figsize=(8,6))

# Puntos dentro de tolerancia (verdes)
plt.scatter(validos["cal_pm25"], validos["ref_pm25"],
            color="green", alpha=0.6, label="Dentro de tolerancia")

# Puntos fuera de tolerancia (rojos)
fuera = df_test.drop(validos.index)
plt.scatter(fuera["cal_pm25"], fuera["ref_pm25"],
            color="red", alpha=0.6, label="Fuera de tolerancia")

# Línea del modelo (predicciones)
plt.plot(X_test, Y_pred, color="blue", linewidth=2, label="Modelo lineal")

plt.xlabel("Sensor (pm25 calibrar)")
plt.ylabel("Referencia (pm25)")
plt.title("Validación del modelo en la segunda mitad (con tolerancia)")
plt.legend()
plt.grid(True)
plt.show()